### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by ferrreo** [PikaOS-Linux/pikaos-site#3]
Add an FAQ section with sensible questions and answers

**Comment by CosmicFusion** [comment]
• Why Ubuntu?

Ubuntu is a very easy to use distribution with the most community support and cooperate support (if you google a proprietary app chances are it's only a deb) so it's the perfect base for our goals, and ubuntu holds a very special place in my heart (Cosmo), and the Launchpad PPA system is really awesome compared to other build systems.

• What is the snap situation on PikaOS?

We have removed snaps from the ISOs, and they will not be forced upon you, firefox and other packages canonical turned into a snap, are now native packages by using it's official source (eg: firefox) or our friends at the xtradeb team (eg: chromium), though if you need snaps they are not completely blocked and can be manually installed.

• Why is apx present on this mutable distribution?

Although i totally see how our user base would never touch apx, I Cosmo require it for my operations (contributing to Nobara, maintaining my AUR submissions), and it has to be configured with the system that's why it's included, and either way it's a nice to have for power users, since they can install any packaging format they want safely (including the aur), and it won't harm or confuse new users since it's clearly marked as subsystem.

• Why do you guys use pikman instead of apt like all the other ubuntu distributions?

apt is very slow! so to have a good experience we need to use nala and we have flatpak and apx scattered everywhere like crazy, so we have 4 package managers at this point which is STUPID, so why not bring them all into one.

• Ubuntu is really slow moving distribution, isn't that terrible for a gaming distro?

While yes that might be true in some cases, we have went through a lot of measures to remidiate this issue by:
• Using a list of very Polished PPA & Official Sources.
• Updating a lot of stuff ourselves.
• Enable proposed and backports repositories which unfreezes the repositories and allows feature updates, while keeping the distro rock stable.

**Comment by gopal-kaul** [comment]
PR #5 addresses this

**Comment by ferrreo** [comment]
Closed - nice work!
